### ISSUE TITLE
A troubleshooting tool built on Pravega CLI

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega-tools#36]
A request to build a Pravega troubleshooting tool for stream specific metadata. The tool will look through the metadata and point out logical faults in the metadata caused due to an unknown bug or environmental fault. The implementation can be as a set of commands in the Pravega CLI.

Following the concepts in this page: https://github.com/anirudhkovuru/pravega/wiki/Pravega-Troubleshoot

**Comment by RaulGracia** [comment]
Any troubleshoot/DR tools should go to the Pravega CLI in the Pravega core repo.
