### ISSUE TITLE
DR: Implement Tier 1/2 Reconciliation

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega-tools#38]
**Problem Description**
Need CLI support for the following Pravega issues:
- https://github.com/pravega/pravega/issues/3992
- https://github.com/pravega/pravega/issues/3993
- https://github.com/pravega/pravega/issues/3994

**Suggestion for Improvement**
Implement the following commands:
- `storage list-segments`: 
    - Invokes https://github.com/pravega/pravega/issues/3994
    - Groups the Segments by Container Id (number of containers is loaded as config)
    - Stores the result either in a memory buffer or on a local file. This data needs to be accessed later, for a different command.
- `container reconcile <container-id>`
    - Invokes https://github.com/pravega/pravega/issues/3993
    - Uses the output from `storage list-segments` to supply to this command.
- `bk reconcile <log-id>`
    - Invokes https://github.com/pravega/pravega/issues/3992

Implement the following combined command:
- `container reconcile-all`
    - Present a clear warning describing what is about to happen.
    - Execute the following (pseudo-script):
```
(<container-count> means the number of containers)

// 1. Disable all Containers - make them enter offline mode.
for <container-id> from 0 to <container-count> {
    bk disable <container-id>
}

// 2. Reconcile all BookKeeperLogs
for <container-id> from 0 to <container-count> {
    bk reconcile <container-id>
}

// 3. Catalog all Tier 2 segments
storage list-segments <segment-list-grouped-by-containerid>

// 4. Reconcile all Segment Containers
for <container-id> from 0 to <container-count> {
    container reconcile <container-id> <segment-list[<container-id>]>
}

// 5. Enable all Segment Containers
for <container-id> from 0 to <container-count> {
    bk enable <container-id>
}

```

Provide enough console output at each step to keep the operator apprised of the progress.

**Comment by naveenkothamasu** [comment]
Addressing the basic scenario of when Tier-1 is completely lost @ #58

**Comment by RaulGracia** [comment]
@andreipaduroiu I assume that we will keep track of this in the DR tool related issues/PRs. Pravega CLI does not belong to this repo any longer.
