### ISSUE TITLE
PasswordFileCreation tool to generate a file based user database for PasswordAuthHandler

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-tools#43]
PasswordFileCreation tool needs to be build based on this class: https://github.com/pravega/pravega/blob/master/controller/src/test/java/io/pravega/controller/auth/PasswordFileCreatorTool.java
to generate a file containing user data, in the same format as this file:
https://github.com/pravega/pravega/blob/master/config/passwd

This generated file can be used as user database for Pravega installation using basic PasswordAuthHandler. See [doc ](https://github.com/pravega/pravega-operator/blob/master/doc/auth.md) for details.

**Comment by RaulGracia** [comment]
Seems that I cannot assign this issue to @ldr7 yet (maybe needs to be part of the org first).
