### ISSUE TITLE
Revisit Pravega CLI to work in environments with security enabled

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-tools#46]
**Problem description**
The Pravega CLI works with plain Pravega deployments. However, its usage when security is enabled is limited (it only deals with Controller REST API authentication). We need to revisit the tool and identify the necessary changes to work in a fully secured Pravega deployment.

**Problem location**
Pravega CLI.

**Suggestions for an improvement**
Enable the tool to work in secured Pravega clusters.

**Comment by EronWright** [comment]
The contours of this appear to be:
1. draw a runtime dependency on the `pravega-keycloak-client` as outlined in [pravega/pravega-keycloak-client](https://github.com/pravega/pravega-keycloak).  Note that it is safe to include this library in all situations; the CLI will still be able to connect to an instance of Pravega that isn't Keycloak-protected.
2. In the CLI's start script, set the environment variables that are needed to activate the Keycloak authentication scheme. 
3. Add a `conf/` directory to the Pravega CLI installation directory, and include its content on the classpath.  The goal would be to include `keycloak.json` on the classpath, which the user would assumedly place in the `conf/` directory.   The `pravega-keycloak-client` library automatically checks the classpath for such a file.   

As for the actual credentials, the `pravega-keycloak-client` library is tested only in conjunction with Keycloak service accounts.  Untested but possible would be to use a Keycloak local user account credential, in the relevant section of `keycloak.json`.

In future, the auth library could be evolved to support OAuth 2.0 flows, as outlined in the [Securing Apps](https://www.keycloak.org/docs/latest/securing_apps/#_installed_adapter) guide.   This would allow the user to use an external identity provider (e.g. UAA), and would essential grant the CLI (which is acting as an OAuth 2.0 client) an access token to act on behalf of the user.
