### ISSUE TITLE
Pravega cli is not giving the complete info about stream cut

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega-tools#48]
Used this pravega image to build cli - `pravega:0.6.0-2391.97363b3`

Build details:-
```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```
Created stream cut using samples tool:-
```
Scope1 >SIMPLE
**** You have selected a simple example to see how Pravega StreamCuts work. Great choice!!
**** Now, we will ask you some questions to set up the example: 

**** How many streams do you want to create? (e.g., from 1 to 5):
simple_example > 1
**** How many events per stream do you want to create? (e.g., from 1 to 20):
simple_example > 5
a0|a1|a2|a3|a4|

**** Your Streams are ready :)

**** Now, to see how StreamCuts work, we are going to build them!
**** [Stream a-264466826259559]  StreamCut start event number.
simple_example > 2
**** [Stream a-264466826259559] StreamCut end event number.
simple_example > 4
**** Now, look! We can print bounded slices of multiple Streams:

**** a2|a3|

```

Describe the complete info about the stream using Pravega cli :-
>controller describe-stream Scope1 a-264466826259559
```
{
  "key": "stream_config",
  "value": {
    "scalingPolicy": {
      "scaleType": "FIXED_NUM_SEGMENTS",
      "targetRate": 0,
      "scaleFactor": 0,
      "minNumSegments": 1
    },
    "timestampAggregationTimeout": 0
  }
}
{
  "key": "stream_state",
  "value": "ACTIVE"
}
{
  "key": "segment_count",
  "value": 1
}
{
  "key": "is_sealed",
  "value": false
}
{
  "key": "active_epoch",
  "value": {
    "epoch": 0,
    "referenceEpoch": 0,
    "segments": [
      {
        "segmentNumber": 0,
        "creationEpoch": 0,
        "creationTime": 1571380997826,
        "keyStart": 0.0,
        "keyEnd": 1.0
      }
    ],
    "creationTime": 1571380997826,
    "segmentIds": [
      0
    ],
    "duplicate": false
  }
}
{
  "key": "truncation_record",
  "value": {
    "streamCut": {},
    "span": {},
    "spanEpochLow": -2147483648,
    "spanEpochHigh": -2147483648,
    "deletedSegments": [],
    "toDelete": [],
    "sizeTill": 0,
    "updating": false
  }
}
{
  "key": "scaling_info",
  "value": [
    {
      "timestamp": 1571380997826,
      "segments": [
        {
          "number": 0,
          "epoch": 0,
          "start": 1571380997826,
          "keyStart": 0.0,
          "keyEnd": 1.0
        }
      ],
      "splits": 0,
      "merges": 0
    }
  ]
}
```

stream cut info is empty array  `"streamCut": {},`

**Comment by RaulGracia** [comment]
@Raghuveera-Rao you are mixing up things here: On the one hand, you have used a sample application that allows you to "generate" StreamCuts; that is, it allows you to bookmark a position in the Stream thanks to a StreamCut (i.e., pairs of segment:offset). This is something that you can generate at the ReaderGroup in your application, but has no effect on the Stream. Is just an abstraction in Pravega to record a point in the Stream while you are reading, that's it.

The `StreamCut` info you believe that is "missing" corresponds to the last truncation point of the Stream (i.e., `truncation_record`). A Stream can be manually truncated at a specific point, or it can be truncated automatically by using a "retention policy". Internally, the Controller stores this point in which the Stream has been truncated as a "truncation record". As the Stream you have described has not been truncated, you see as empty the truncation record, which is correct.

However, both things have nothing to do. Hope that the explanation is clear enough.
