### ISSUE TITLE
Simplified, resource-based provisioning model

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-tools#55]
**Problem description**
The current provisioning model is complex and takes into account multiple factors, including redundancy and performance expectations. We need a simplified version of this model that just attempts to use all the resources of the cluster, based on some "ratios" (e.g., Bookies to Segment Stores, Controllers to Segment Stores) of that relate the different instance types.

**Problem location**
Provisioning model.

**Suggestions for an improvement**
Extend the current provisioning model with a resource-based approach that maximizes utilization.

**Comment by gaddamas** [comment]
would it be better to output the expected resources along with the error message if minimal cluster can't be created with given resources.

**Comment by RaulGracia** [comment]
Closed via #57 .
