### ISSUE TITLE
Update Segment Container Metadata

### ISSUE THREAD

**Issue by naveenkothamasu** [pravega/pravega-tools#58]
**Problem description**
The following is addressing a scenario when all of Tier-1 data is lost.
To address #38, along with [#3994](https://github.com/pravega/pravega/issues/3994), we need a way to fix the Tier-1 data based off of Tier-2 data.

**Problem location**
Segment Store.

**Suggestions for an improvement**
`pravega-cli` starts the container in "Debug" mode in order to execute the createSegment with pre-defined state.
The general outline is the following. 
```
(pravega)
Create DebugStreamSegmentContainer#createSegment(name, length, isSealed)
(pravega-cli) 
for containerId =0 to n-1
	DSC = streamSegmentContainerFactory.createDebugStreamSegmentContainer(containerId)
	Services.startAsync(DSC, executorService());
	for each segment in Tier-2 listing for this container 
    	createSegment(name, length, isSealed)
	for each segment in the old container metadata (that file previously renamed in Tier 2)
    	If the Segment exists in the Container (above loop), 
    		seal(segmentId, timeout) 
    		updateAttributesForSegment(segmentId, attributeUpdates, timeout)
```

**Comment by RaulGracia** [comment]
@ManishKumarKeshri is this issue still valid or these DR issues are replaced with the issues in Pravega core repo? If they are duplicated, let's close them.

**Comment by RaulGracia** [comment]
@ManishKumarKeshri if this is still an issue to resolve, please port it to the Pravega core repo and keep track of all DR-related tasks there jointly with CLI.
