### ISSUE TITLE
Pravega CLI should allow users to create and drop scope and streams

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega-tools#70]
Currently (0.7.1) there is no easy way to create a scope and a stream manually.
This is very awkward for users.

A full cli-based scope/stream manager would be great but at least we need some way to create scopes and streams, setting all of the relevant configuration options and a way to drop them.

**Comment by Ranganaths8** [comment]
you can create scope & stream via REST API http://pravega.io/docs/latest/rest/restapis/#post-scopes & http://pravega.io/docs/latest/rest/restapis/#post-scopesscopenamestreams today to create scopes & streams respectively. please check out the  controller REST API documentation.

**Comment by RaulGracia** [comment]
This is fixed with the User CLI contributed in this PR: https://github.com/pravega/pravega/pull/5065.
